---
- name: update packages
  yum:
    name: '*'
    state: latest
  tags: [update_pkd]
- name: install postfix
  yum:
    name: postfix
    state: present
    notify: Restart postfix
  tags: [install_postfix]
- name: Add gitlab-ce repo
  shell: curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash
  tags: [add_repo]
- name: install gitlab
  yum:
    name: gitlab-ce
    state: present
  tags: [install_gitlab]
- name: Add External URL
  shell: sed -i 's/^external_url 'http://gitlab.example.com'$/external_url 'http://git.nazarbazi.com'/' /etc/gitlab/gitlab.rb
  tags: [add_url]
- name: reconfigure gitlab
  shell: gitlab-ctl reconfigure
  tags: [reconfig-git]
- name: install Certbot
  get_url:
    - url: https://dl.eff.org/certbot-auto
      dest: /usr/local/bin/certbot-auto
      chown: root
      mode: 0755
  tags: [get-certbot]
- name: deploy gitlab with ssl/tls
  shell: sed -i 's/^external_url 'http://git.nazarbazi.com'$/external_url 'https://git.nazarbazi.com'/' /etc/gitlab/gitlab.rb
  tags: [change_url]
- name: add Let's Encrypt
  shell: sed '/external_url/ i "letsencrypt['enable'] = true"' /etc/gitlab/gitlab.rb
  tags: [enable_lets-encrypt]
  